/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTColor.h"
#import "NTBitmap.h"
#import "NTPopupStyle.h"

/**
 * Margins info for balloon popup.
 */
__attribute__ ((visibility("default"))) @interface NTBalloonPopupMargins : NSObject
{
	/** @internal:nodoc: */
	void *swigCPtr;
	/** @internal:nodoc: */
	BOOL swigCMemOwn;
}
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)initWithLeft: (int)left top: (int)top right: (int)right bottom: (int)bottom;
-(int)getLeft;
-(int)getTop;
-(int)getRight;
-(int)getBottom;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;

-(void)dealloc;

@end


#import "NTColor.h"
#import "NTBitmap.h"
#import "NTPopupStyle.h"

/**
 * A style for balloon popups. Contains attributes for configuring how the balloon popup is drawn on the screen.
 */
__attribute__ ((visibility("default"))) @interface NTBalloonPopupStyle : NTPopupStyle
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 * @param cPtr The native pointer of the instance.
 * @param cMemoryOwn The ownership flag.
 * @return The new instance.
 */
/** @internal:nodoc: */
+(NTBalloonPopupStyle*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Returns the background color of the popup.<br>
 * @return The background color of the popup.
 */
-(NTColor*)getBackgroundColor;
/**
 * Returns the corner radius of the popup.<br>
 * @return The corner radius of the popup.
 */
-(int)getCornerRadius;
/**
 * Returns the background color of the left part of the popup.<br>
 * @return The background color of the left part of the popup.
 */
-(NTColor*)getLeftColor;
/**
 * Returns the image of the left part of the popup.<br>
 * @return The image of the left part of the popup.
 */
-(NTBitmap*)getLeftImage;
/**
 * Returns the margins of the left part of the popup.<br>
 * @return The margins of the left part of the popup.
 */
-(NTBalloonPopupMargins*)getLeftMargins;
/**
 * Returns the background color of the right part of the popup.<br>
 * @return The background color of the right part of the popup.
 */
-(NTColor*)getRightColor;
/**
 * Returns the image of the right part of the popup.<br>
 * @return The image of the right part of the popup.
 */
-(NTBitmap*)getRightImage;
/**
 * Returns the margins of the right part of the popup.<br>
 * @return The margins of the right part of the popup.
 */
-(NTBalloonPopupMargins*)getRightMargins;
/**
 * Returns the color of the title.<br>
 * @return The color of the title.
 */
-(NTColor*)getTitleColor;
/**
 * Returns the name of the title font.<br>
 * @return The name of the title font.
 */
-(NSString*)getTitleFontName;
/**
 * Returns the title field variable to use.<br>
 * @return The title field variable.
 */
-(NSString*)getTitleField;
/**
 * Returns the size of the title font.<br>
 * @return The size of the title font.
 */
-(int)getTitleFontSize;
/**
 * Returns the margins of the title.<br>
 * @return The margins of the title.
 */
-(NTBalloonPopupMargins*)getTitleMargins;
/**
 * Returns the state of the title wrap parameter.<br>
 * @return True if long titles are wrapped, false if it is truncated.
 */
-(BOOL)isTitleWrap;
/**
 * Returns the color of the description.<br>
 * @return The color of the description.
 */
-(NTColor*)getDescriptionColor;
/**
 * Returns the name of the description font.<br>
 * @return The name of the description font.
 */
-(NSString*)getDescriptionFontName;
/**
 * Returns the description field variable to use.<br>
 * @return The description field variable.
 */
-(NSString*)getDescriptionField;
/**
 * Returns the size of the description font.<br>
 * @return The size of the description font.
 */
-(int)getDescriptionFontSize;
/**
 * Returns the margins of the description.<br>
 * @return The margins of the description.
 */
-(NTBalloonPopupMargins*)getDescriptionMargins;
/**
 * Returns the state of the description wrap parameter.<br>
 * @return True if long descriptions are wrapped, false if it is truncated.
 */
-(BOOL)isDescriptionWrap;
/**
 * Returns the color of the stroke surrounding the popup.<br>
 * @return The color of the stroke surrounding the popup.
 */
-(NTColor*)getStrokeColor;
/**
 * Returns the width of the stroke surrounding the popup.<br>
 * @return The width of the stroke surrounding the popup in dp.
 */
-(int)getStrokeWidth;
/**
 * Returns the width of the triangle at the bottom of the popup.<br>
 * @return The width of the triangle at the bottom of the popup in dp.
 */
-(int)getTriangleWidth;
/**
 * Returns the height of the triangle at the bottom of the popup.<br>
 * @return The height of the triangle at the bottom of the popup in dp.
 */
-(int)getTriangleHeight;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
/** @internal:nodoc: */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
/** @internal:nodoc: */
-(void *)swigGetDirectorObject;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

