/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTBitmap.h"
#import <UIKit/UIKit.h>

/**
 * A helper class for loading bitmaps and converting Bitmaps to UIImages an vice versa.
 */
__attribute__ ((visibility("default"))) @interface NTBitmapUtils : NSObject
{
	/** @internal:nodoc: */
	void *swigCPtr;
	/** @internal:nodoc: */
	BOOL swigCMemOwn;
}
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Loads the specified bitmap asset bundled with the application.<br>
 * @param assetPath The asset path to the image to be loaded.<br>
 * @return The loaded bitmap.
 */
+(NTBitmap*)loadBitmapFromAssets: (NSString*)assetPath;
/**
 * Loads bitmap from specified file.<br>
 * @param filePath The path to the image to be loaded.<br>
 * @return The loaded bitmap.
 */
+(NTBitmap*)loadBitmapFromFile: (NSString*)filePath;
/**
 * Creates a new Bitmap object from an existing UIImage.<br>
 * @param image The reference UIImage.<br>
 * @return The created bitmap.
 */
+(NTBitmap*)createBitmapFromUIImage: (UIImage*)image;
/**
 * Creates a new UIImage object from an existing Bitmap.<br>
 * @param bitmap The reference bitmap.<br>
 * @return The created UIImage.
 */
+(UIImage*)createUIImageFromBitmap: (NTBitmap*)bitmap;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

