/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif

/**
 * Built-in Carto basemap styles.
 */
typedef NS_ENUM(NSInteger, NTCartoBaseMapStyle) {
/**
 * The Positron style. Replacement for older 'grey' style.
 */
  NT_CARTO_BASEMAP_STYLE_POSITRON,
/**
 * The Darkmatter style. Replacement for older 'dark' style.
 */
  NT_CARTO_BASEMAP_STYLE_DARKMATTER,
/**
 * The Voyager style. Replacement for older 'bright' style.
 */
  NT_CARTO_BASEMAP_STYLE_VOYAGER
};


#import "NTTileDataSource.h"
#import "NTVectorTileLayer.h"
#import "NTAssetPackage.h"
#import "NTVectorTileDecoder.h"

/**
 * Specialized vector tile layer that can use built-in vector tile styles.
 */
__attribute__ ((visibility("default"))) @interface NTCartoVectorTileLayer : NTVectorTileLayer
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 * @param cPtr The native pointer of the instance.
 * @param cMemoryOwn The ownership flag.
 * @return The new instance.
 */
/** @internal:nodoc: */
+(NTCartoVectorTileLayer*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a CartoVectorTileLayer object from a specificed base map style.<br>
 * @param dataSource The data source from which this layer loads data.<br>
 * @param style The style to use for the layer.
 */
-(id)initWithDataSource: (NTTileDataSource*)dataSource style: (enum NTCartoBaseMapStyle)style;
/**
 * Constructs a CartoVectorTileLayer object from a source name and a style asset package.<br>
 * Style asset package defines visual style of the map and must be compatible with the source.<br>
 * @param dataSource The data source from which this layer loads data.<br>
 * @param styleAssetPackage The style asset package (usually a zipped file or an asset)
 */
-(id)initWithDataSource: (NTTileDataSource*)dataSource styleAssetPackage: (NTAssetPackage*)styleAssetPackage;
/**
 * Constructs a CartoVectorTileLayer object from a source name and a style asset package.<br>
 * Style asset package defines visual style of the map and must be compatible with the source.<br>
 * @param dataSource The data source from which this layer loads data.<br>
 * @param styleAssetPackage The style asset package (usually a zipped file or an asset)<br>
 * @param styleName The style to use from the asset package.
 */
-(id)initWithDataSource: (NTTileDataSource*)dataSource styleAssetPackage: (NTAssetPackage*)styleAssetPackage styleName: (NSString*)styleName;
/**
 * Returns the current language used for the layer.<br>
 * @return The current language. If the returned string is empty, then 'local' languages are used.
 */
-(NSString*)getLanguage;
/**
 * Sets the current map language.<br>
 * @param lang The new language to use. The default is local language (empty string).
 */
-(void)setLanguage: (NSString*)lang;
/**
 * Returns the current fallback language used for the layer. Fallback language is used when a primary language name is not available.<br>
 * @return The current fallback language. If the returned string is empty, then 'local' languages are used.
 */
-(NSString*)getFallbackLanguage;
/**
 * Sets the current fallback map language. Fallback language is used when a primary language name is not available.<br>
 * @param lang The new fallback language to use. The default is local language (empty string).
 */
-(void)setFallbackLanguage: (NSString*)lang;
/**
 * Creates a new tile decoder from the specified base map style.<br>
 * @param style The style to use for the decoder.<br>
 * @return The new vector tile decoder configured for the style.
 */
+(NTVectorTileDecoder*)createTileDecoderFromStyle: (enum NTCartoBaseMapStyle)style;
/**
 * Creates a new tile decoder from the specified asset package.<br>
 * @param styleAssetPackage The style asset package (usually a zipped file or an asset)<br>
 * @return The new vector tile decoder configured for the style.
 */
+(NTVectorTileDecoder*)createTileDecoderFromAssetPackage: (NTAssetPackage*)styleAssetPackage;
/**
 * Creates a new tile decoder from the specified asset package.<br>
 * @param styleAssetPackage The style asset package (usually a zipped file or an asset)<br>
 * @param styleName The name of the style to use.<br>
 * @return The new vector tile decoder configured for the style.
 */
+(NTVectorTileDecoder*)createTileDecoder: (NTAssetPackage*)styleAssetPackage styleName: (NSString*)styleName;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
/** @internal:nodoc: */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
/** @internal:nodoc: */
-(void *)swigGetDirectorObject;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

