/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif

/**
 * Possible click types.
 */
typedef NS_ENUM(NSInteger, NTClickType) {
/**
 * A click caused by pressing down and then releasing the screen.
 */
  NT_CLICK_TYPE_SINGLE,
/**
 * A click caused by pressing down but not releasing the screen.
 */
  NT_CLICK_TYPE_LONG,
/**
 * A click caused by two fast consecutive taps on the screen.
 */
  NT_CLICK_TYPE_DOUBLE,
/**
 * A click caused by two simultaneous taps on the screen.
 */
  NT_CLICK_TYPE_DUAL
};


#ifdef __cplusplus
}
#endif

