/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTAssetPackage.h"

/**
 * Compiled style set definition for vector tiles. Compiled style sets should contains either Mapnik XML stylesheets<br>
 * with all required assets or CartoCSS JSON-based project files.
 */
__attribute__ ((visibility("default"))) @interface NTCompiledStyleSet : NSObject
{
  /** @internal:nodoc: */
  void *swigCPtr;
  /** @internal:nodoc: */
  BOOL swigCMemOwn;
}
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**  
 * Checks if this object is equal to the specified object.
 * @param object The reference object.
 * @return True when objects are equal, false otherwise.
 */
-(BOOL)isEqual:(id)object;

/**
 * Returns the hash value of this object.
 * @return The hash value of this object.
 */
-(NSUInteger)hash;

/**
 * Constructs a style set from the given asset package.<br>
 * If the asset package contains multiple styles (XML or JSON files), the first one (based on lexicographical order) from the root folder is chosen as the current style.<br>
 * @param assetPackage The asset package containing compiled style set data and style definition.
 */
-(id)initWithAssetPackage: (NTAssetPackage*)assetPackage;
/**
 * Constructs a style from the given asset package and explicit style name.<br>
 * @param assetPackage The asset package containing compiled style set data and style definition.<br>
 * @param styleName The name of the style to use.
 */
-(id)initWithAssetPackage: (NTAssetPackage*)assetPackage styleName: (NSString*)styleName;
/**
 * Returns the current style name.<br>
 * @return The current style name.
 */
-(NSString*)getStyleName;
/**
 * Returns the asset name defining the current style name.<br>
 * @return The CartoCSS string used for the style.<br>
 * @return The asset name defining the current style name.
 */
-(NSString*)getStyleAssetName;
/**
 * Returns the style asset package.<br>
 * @return The style asset package.
 */
-(NTAssetPackage*)getAssetPackage;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

