/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTVectorDataSource.h"
#import "NTVectorLayer.h"
#import "NTVectorEditEventListener.h"
#import "NTVectorElement.h"

/**
 * A vector layer that supports editing its contents. Editing requires registered listener.
 */
__attribute__ ((visibility("default"))) @interface NTEditableVectorLayer : NTVectorLayer
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 * @param cPtr The native pointer of the instance.
 * @param cMemoryOwn The ownership flag.
 * @return The new instance.
 */
/** @internal:nodoc: */
+(NTEditableVectorLayer*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a VectorLayer object from a data source.<br>
 * @param dataSource The data source from which this layer loads data.
 */
-(id)initWithDataSource: (NTVectorDataSource*)dataSource;
/**
 * Returns the selected vector element. If no element is currently selected, null is returned.<br>
 * @return The selected vector element or null if no element is selected.
 */
-(NTVectorElement*)getSelectedVectorElement;
/**
 * Selects the given vector element. Deselects currently selected element is null argument is used.<br>
 * @param element The vector element to select or null.
 */
-(void)setSelectedVectorElement: (NTVectorElement*)element;
/**
 * Returns the current edit event listener for the layer.<br>
 * @return The current edit event listener or null if no listener is set.
 */
-(NTVectorEditEventListener*)getVectorEditEventListener;
/**
 * Sets the current edit event listener for the layer. <br>
 * Note that valid listener is required for editing operations to work.<br>
 * @param listener The edit event listener to use.
 */
-(void)setVectorEditEventListener: (NTVectorEditEventListener*)listener;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
/** @internal:nodoc: */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
/** @internal:nodoc: */
-(void *)swigGetDirectorObject;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

