/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif

/**
 * Listener for specific map renderer events.
 */
__attribute__ ((visibility("default"))) @interface NTMapRendererListener : NSObject
{
  /** @internal:nodoc: */
  void *swigCPtr;
  /** @internal:nodoc: */
  BOOL swigCMemOwn;
}
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 * @param cPtr The native pointer of the instance.
 * @param cMemoryOwn The ownership flag.
 * @return The new instance.
 */
/** @internal:nodoc: */
+(NTMapRendererListener*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Listener method that gets called at the start of the rendering process.<br>
 * The method can be used to synchronize vector elements with renderer state, for example<br>
 * to force marker to be always at the center of the screen (focus point).<br>
 * This method is called from GL renderer thread, not from main thread.
 */
-(void)onBeforeDrawFrame;
/**
 * Listener method that gets called at the start of the rendering process.<br>
 * The method can be used to synchronize vector elements with renderer state, for example<br>
 * to force marker to be always at the center of the screen (focus point).<br>
 * This method is called from GL renderer thread, not from main thread.
 */
-(void)onBeforeDrawFrameSwigExplicitNTMapRendererListener;
/**
 * Listener method that gets called at the end of the rendering process.<br>
 * This method is called from GL renderer thread, not from main thread.
 */
-(void)onAfterDrawFrame;
/**
 * Listener method that gets called at the end of the rendering process.<br>
 * This method is called from GL renderer thread, not from main thread.
 */
-(void)onAfterDrawFrameSwigExplicitNTMapRendererListener;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
/** @internal:nodoc: */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
/** @internal:nodoc: */
-(void *)swigGetDirectorObject;
-(id)init;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

