/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTReverseGeocodingService.h"
#import "NTReverseGeocodingRequest.h"
#import "NTGeocodingResult.h"
#import "NTProjection.h"

/**
 * A reverse geocoding service that uses custom geocoding database files.<br>
 * Note: this class is experimental and may change or even be removed in future SDK versions.
 */
__attribute__ ((visibility("default"))) @interface NTOSMOfflineReverseGeocodingService : NTReverseGeocodingService
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 * @param cPtr The native pointer of the instance.
 * @param cMemoryOwn The ownership flag.
 * @return The new instance.
 */
/** @internal:nodoc: */
+(NTOSMOfflineReverseGeocodingService*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a new instance of the OSMOfflineReverseGeocodingService given path to the geocoding database.<br>
 * @param path The full path to the geocoding database file.<br>
 * @throws NSException If the database file could not be opened or read.
 */
-(id)initWithPath: (NSString*)path;
/**
 * Returns the language of the expected results.<br>
 * @return The language of the expected results. As ISO 639-1 code or empty string.
 */
-(NSString*)getLanguage;
/**
 * Sets the language of the expected results.<br>
 * @param lang The language to use as ISO 639-1 code. Empty string can be used for default language.
 */
-(void)setLanguage: (NSString*)lang;
-(NTGeocodingResultVector*)calculateAddresses: (NTReverseGeocodingRequest*)request;
-(NTGeocodingResultVector*)calculateAddressesSwigExplicitNTOSMOfflineReverseGeocodingService: (NTReverseGeocodingRequest*)request;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
/** @internal:nodoc: */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
/** @internal:nodoc: */
-(void *)swigGetDirectorObject;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

