/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTGeocodingService.h"
#import "NTGeocodingRequest.h"
#import "NTGeocodingResult.h"
#import "NTPackageManager.h"
#import "NTProjection.h"

/**
 * A geocoding service that uses geocoding packages from package manager.
 */
__attribute__ ((visibility("default"))) @interface NTPackageManagerGeocodingService : NTGeocodingService
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 * @param cPtr The native pointer of the instance.
 * @param cMemoryOwn The ownership flag.
 * @return The new instance.
 */
/** @internal:nodoc: */
+(NTPackageManagerGeocodingService*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a new instance of the PackageManagerGeocodingService given package manager instance.<br>
 * @param packageManager The package manager instance to use.
 */
-(id)initWithPackageManager: (NTPackageManager*)packageManager;
/**
 * Returns the autocomplete flag of the service.<br>
 * @return The autocomplete flag of the service.
 */
-(BOOL)isAutocomplete;
/**
 * Sets the autocomplete flag of the service.<br>
 * By default this flag is off.<br>
 * @param autocomplete The new value for autocomplete flag.
 */
-(void)setAutocomplete: (BOOL)autocomplete;
/**
 * Returns the language of the expected results.<br>
 * @return The language of the expected results. As ISO 639-1 code or empty string.
 */
-(NSString*)getLanguage;
/**
 * Sets the language of the expected results.<br>
 * @param lang The language to use as ISO 639-1 code. Empty string can be used for default language.
 */
-(void)setLanguage: (NSString*)lang;
-(NTGeocodingResultVector*)calculateAddresses: (NTGeocodingRequest*)request;
-(NTGeocodingResultVector*)calculateAddressesSwigExplicitNTPackageManagerGeocodingService: (NTGeocodingRequest*)request;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
/** @internal:nodoc: */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
/** @internal:nodoc: */
-(void *)swigGetDirectorObject;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

