/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTMapPos.h"
#import "NTMapBounds.h"
#import "NTMapTile.h"
#import "NTProjection.h"

/**
 * A helper class for mapping coordinates to tiles and back.
 */
__attribute__ ((visibility("default"))) @interface NTTileUtils : NSObject
{
	/** @internal:nodoc: */
	void *swigCPtr;
	/** @internal:nodoc: */
	BOOL swigCMemOwn;
}
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Calculates the map tile corresponding to specified point and zoom level.<br>
 * @param mapPos Coordinates for the point.<br>
 * @param zoom Zoom level for the tile.<br>
 * @param proj The projection to use for tile and point.<br>
 * @return The corresponding map tile.
 */
+(NTMapTile*)calculateMapTile: (NTMapPos*)mapPos zoom: (int)zoom proj: (NTProjection*)proj;
/**
 * Calculates origin coordinates for the given map tile.<br>
 * @param mapTile The map tile to use.<br>
 * @param proj The projection to use for origin.<br>
 * @return The corresponding tile origin.
 */
+(NTMapPos*)calculateMapTileOrigin: (NTMapTile*)mapTile proj: (NTProjection*)proj;
/**
 * Calculates bounds for the given map tile.<br>
 * @param mapTile The map tile to use.<br>
 * @param proj The projection to use for bounds.<br>
 * @return The corresponding tile bounds.
 */
+(NTMapBounds*)calculateMapTileBounds: (NTMapTile*)mapTile proj: (NTProjection*)proj;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

