/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTMapTile.h"

/**
 * Listener for tile downloader.
 */
__attribute__ ((visibility("default"))) @interface NTTileDownloadListener : NSObject
{
  /** @internal:nodoc: */
  void *swigCPtr;
  /** @internal:nodoc: */
  BOOL swigCMemOwn;
}
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 * @param cPtr The native pointer of the instance.
 * @param cMemoryOwn The ownership flag.
 * @return The new instance.
 */
/** @internal:nodoc: */
+(NTTileDownloadListener*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Listener method that is called before download has actually started to report the total tile count.<br>
 * @param tileCount The number of tiles that will be downloaded (if not already in the cache).
 */
-(void)onDownloadStarting: (int)tileCount;
/**
 * Listener method that is called before download has actually started to report the total tile count.<br>
 * @param tileCount The number of tiles that will be downloaded (if not already in the cache).
 */
-(void)onDownloadStartingSwigExplicitNTTileDownloadListener: (int)tileCount;
/**
 * Listener method that is called to report about download progress.<br>
 * @param progress The progress of the download, from 0 to 100.
 */
-(void)onDownloadProgress: (float)progress;
/**
 * Listener method that is called to report about download progress.<br>
 * @param progress The progress of the download, from 0 to 100.
 */
-(void)onDownloadProgressSwigExplicitNTTileDownloadListener: (float)progress;
/**
 * Listener method that is called when downloading has finished.
 */
-(void)onDownloadCompleted;
/**
 * Listener method that is called when downloading has finished.
 */
-(void)onDownloadCompletedSwigExplicitNTTileDownloadListener;
/**
 * Listener method that is called when a tile download fails.<br>
 * @param tile The tile that could not be downloaded.
 */
-(void)onDownloadFailed: (NTMapTile*)tile;
/**
 * Listener method that is called when a tile download fails.<br>
 * @param tile The tile that could not be downloaded.
 */
-(void)onDownloadFailedSwigExplicitNTTileDownloadListener: (NTMapTile*)tile;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
/** @internal:nodoc: */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
/** @internal:nodoc: */
-(void *)swigGetDirectorObject;
-(id)init;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

