/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTUTFGridClickInfo.h"

/**
 * Listener for vector element events like clicks etc.
 */
__attribute__ ((visibility("default"))) @interface NTUTFGridEventListener : NSObject
{
  /** @internal:nodoc: */
  void *swigCPtr;
  /** @internal:nodoc: */
  BOOL swigCMemOwn;
}
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 * @param cPtr The native pointer of the instance.
 * @param cMemoryOwn The ownership flag.
 * @return The new instance.
 */
/** @internal:nodoc: */
+(NTUTFGridEventListener*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Listener method that gets called when a click is performed on an UTF grid element.<br>
 * If the method returns true, all subsequent layers are ignored and click event is not passed down.<br>
 * This method will NOT be called from the main thread.<br>
 * @param clickInfo A container that provides information about the click.<br>
 * @return True if the click is handled and subsequent layers do not need to be notified.
 */
-(BOOL)onUTFGridClicked: (NTUTFGridClickInfo*)clickInfo;
/**
 * Listener method that gets called when a click is performed on an UTF grid element.<br>
 * If the method returns true, all subsequent layers are ignored and click event is not passed down.<br>
 * This method will NOT be called from the main thread.<br>
 * @param clickInfo A container that provides information about the click.<br>
 * @return True if the click is handled and subsequent layers do not need to be notified.
 */
-(BOOL)onUTFGridClickedSwigExplicitNTUTFGridEventListener: (NTUTFGridClickInfo*)clickInfo;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
/** @internal:nodoc: */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
/** @internal:nodoc: */
-(void *)swigGetDirectorObject;
-(id)init;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

