/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTRoutingService.h"
#import "NTRoutingRequest.h"
#import "NTRoutingResult.h"
#import "NTRouteMatchingRequest.h"
#import "NTRouteMatchingResult.h"

/**
 * An offline routing service that uses Valhalla routing tiles.
 */
__attribute__ ((visibility("default"))) @interface NTValhallaOfflineRoutingService : NTRoutingService
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 * @param cPtr The native pointer of the instance.
 * @param cMemoryOwn The ownership flag.
 * @return The new instance.
 */
/** @internal:nodoc: */
+(NTValhallaOfflineRoutingService*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a new ValhallaOfflineRoutingService instance given database file.<br>
 * @param path The full path to the database file.<br>
 * @throws NSException If the database file could not be opened or read.
 */
-(id)initWithPath: (NSString*)path;
/**
 * Returns the current routing profile.<br>
 * @return The current routing profile. Can be either "auto", "bicycle", "pedestrian" or "multimodal". The default is "pedestrian".
 */
-(NSString*)getProfile;
/**
 * Sets the current routing profile.<br>
 * @param profile The new profile. Can be either "auto", "bicycle", "pedestrian" or "multimodal".
 */
-(void)setProfile: (NSString*)profile;
/**
 * Matches specified points to the points on road network.<br>
 * @param request The matching request.<br>
 * @return The matching result or null if route matching failed.<br>
 * @throws NSException If IO error occured during the route matching.
 */
-(NTRouteMatchingResult*)matchRoute: (NTRouteMatchingRequest*)request;
-(NTRoutingResult*)calculateRoute: (NTRoutingRequest*)request;
-(NTRoutingResult*)calculateRouteSwigExplicitNTValhallaOfflineRoutingService: (NTRoutingRequest*)request;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
/** @internal:nodoc: */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
/** @internal:nodoc: */
-(void *)swigGetDirectorObject;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

