/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTSearchRequest.h"
#import "NTVectorDataSource.h"
#import "NTVectorElement.h"
#import "NTProjection.h"
@class NTVectorElementVector;

/**
 * A search service for finding vector elements from the specified vector data source.
 */
__attribute__ ((visibility("default"))) @interface NTVectorElementSearchService : NSObject
{
  /** @internal:nodoc: */
  void *swigCPtr;
  /** @internal:nodoc: */
  BOOL swigCMemOwn;
}
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 * @param cPtr The native pointer of the instance.
 * @param cMemoryOwn The ownership flag.
 * @return The new instance.
 */
/** @internal:nodoc: */
+(NTVectorElementSearchService*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a VectorElementSearchService for the given vector data source.<br>
 * @param dataSource The vector data source to search from.
 */
-(id)initWithDataSource: (NTVectorDataSource*)dataSource;
/**
 * Returns the vector data source of the search service.<br>
 * @return The vector data source of the search service.
 */
-(NTVectorDataSource*)getDataSource;
/**
 * Searches for the vector elements specified by search request from the data source bound to the service.<br>
 * @param request The search request containing search filters.<br>
 * @return The resulting list of vector elements matching the request.
 */
-(NTVectorElementVector*)findElements: (NTSearchRequest*)request;
/**
 * Searches for the vector elements specified by search request from the data source bound to the service.<br>
 * @param request The search request containing search filters.<br>
 * @return The resulting list of vector elements matching the request.
 */
-(NTVectorElementVector*)findElementsSwigExplicitNTVectorElementSearchService: (NTSearchRequest*)request;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
/** @internal:nodoc: */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
/** @internal:nodoc: */
-(void *)swigGetDirectorObject;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

