/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTAssetPackage.h"

/**
 * CartoCSS style definition for vector tiles. Style sets contain optional asset package,<br>
 * fonts and other resources can be loaded from the asset package.
 */
__attribute__ ((visibility("default"))) @interface NTCartoCSSStyleSet : NSObject
{
  /** @internal:nodoc: */
  void *swigCPtr;
  /** @internal:nodoc: */
  BOOL swigCMemOwn;
}
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**  
 * Checks if this object is equal to the specified object.
 * @param object The reference object.
 * @return True when objects are equal, false otherwise.
 */
-(BOOL)isEqual:(id)object;

/**
 * Returns the hash value of this object.
 * @return The hash value of this object.
 */
-(NSUInteger)hash;

/**
 * Constructs a style from CartoCSS string.<br>
 * @param cartoCSS The CartoCSS string defining point styling.
 */
-(id)initWithCartoCSS: (NSString*)cartoCSS;
/**
 * Constructs a style from CartoCSS string and asset data.<br>
 * @param cartoCSS The CartoCSS string defining point styling.<br>
 * @param assetPackage The optional asset package for the style. Can be null if CartoCSS does not use any local assets.
 */
-(id)initWithCartoCSS: (NSString*)cartoCSS assetPackage: (NTAssetPackage*)assetPackage;
/**
 * Returns the CartoCSS string used for the style.<br>
 * @return The CartoCSS string used for the style.
 */
-(NSString*)getCartoCSS;
/**
 * Returns the style asset package.<br>
 * @return The style asset package.
 */
-(NTAssetPackage*)getAssetPackage;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;

-(void)dealloc;

@end


#import "NTAssetPackage.h"

__attribute__ ((visibility("default"))) @interface NTStringCartoCSSStyleSetMap : NSObject
{
	/** @internal:nodoc: */
	void *swigCPtr;
	/** @internal:nodoc: */
	BOOL swigCMemOwn;
}
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;
-(id)initWithArg0: (NTStringCartoCSSStyleSetMap*)arg0;
-(unsigned int)size;
-(BOOL)empty;
-(void)clear;
-(NTCartoCSSStyleSet*)get: (NSString*)key;
-(void)set: (NSString*)key x: (NTCartoCSSStyleSet*)x;
-(void)del: (NSString*)key;
-(BOOL)has_key: (NSString*)key;
-(NSString*)get_key: (unsigned int)idx;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

