/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTMapPos.h"
#import "NTProjection.h"

/**
 * A geocoding request describing text-based query and other optional constraints.
 */
__attribute__ ((visibility("default"))) @interface NTGeocodingRequest : NSObject
{
  /** @internal:nodoc: */
  void *swigCPtr;
  /** @internal:nodoc: */
  BOOL swigCMemOwn;
}
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**  
 * Checks if this object is equal to the specified object.
 * @param object The reference object.
 * @return True when objects are equal, false otherwise.
 */
-(BOOL)isEqual:(id)object;

/**
 * Returns the hash value of this object.
 * @return The hash value of this object.
 */
-(NSUInteger)hash;

/**
 * Constructs a new GeocodingRequest object from a projection and a string-based query.<br>
 * @param projection The projection to use for the result and location data.<br>
 * @param query The text-based query.
 */
-(id)initWithProjection: (NTProjection*)projection query: (NSString*)query;
/**
 * Returns the text-based query of the request.<br>
 * @return The text-based query of the request.
 */
-(NSString*)getQuery;
/**
 * Returns the projection of the request.<br>
 * @return The projection of the request.
 */
-(NTProjection*)getProjection;
/**
 * Returns the location attribute of the request.<br>
 * The matching address near the specified location (up to a specified radius) are preferred.<br>
 * @return The location attribute of the request.
 */
-(NTMapPos*)getLocation;
/**
 * Sets the location attribute of the request.<br>
 * The matching address near the specified location (up to a specified radius) are preferred.<br>
 * @param pos The new location for the request.
 */
-(void)setLocation: (NTMapPos*)pos;
/**
 * Returns the location radius attribute of the request (in meters).<br>
 * @return The location radius attribute of the request in meters.
 */
-(float)getLocationRadius;
/**
 * Sets the location radius attribute of the request.<br>
 * The default is 0, which means that location based ranking is not applied.<br>
 * @param radius The location radius attribute of the request in meters.
 */
-(void)setLocationRadius: (float)radius;
/**
 * Creates a string representation of this request object, useful for logging.<br>
 * @return The string representation of this request object.
 */
-(NSString*)description;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

