/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif

/**
 * Tile status.
 */
typedef NS_ENUM(NSInteger, NTPackageTileStatus) {
/**
 * Tile is not part of the package.
 */
  NT_PACKAGE_TILE_STATUS_MISSING,
/**
 * Tile is part of the package, but package does not fully cover it.<br>
 * This value is no longer used, thus this is deprecated.
 */
  NT_PACKAGE_TILE_STATUS_PARTIAL,
/**
 * Tile if part of the package and package fully covers it.
 */
  NT_PACKAGE_TILE_STATUS_FULL
};


#import "NTMapTile.h"
#import "NTMultiPolygonGeometry.h"
#import "NTProjection.h"

/**
 * Tile mask contains map package spatial coverage information and<br>
 * can be used for very fast 'tile in package' tests.
 */
__attribute__ ((visibility("default"))) @interface NTPackageTileMask : NSObject
{
  /** @internal:nodoc: */
  void *swigCPtr;
  /** @internal:nodoc: */
  BOOL swigCMemOwn;
}
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**  
 * Checks if this object is equal to the specified object.
 * @param object The reference object.
 * @return True when objects are equal, false otherwise.
 */
-(BOOL)isEqual:(id)object;

/**
 * Returns the hash value of this object.
 * @return The hash value of this object.
 */
-(NSUInteger)hash;

/**
 * Returns the encoded tile mask value. This should not be displayed to the user.<br>
 * @return The tile mask of the package.
 */
-(NSString*)getStringValue;
/**
 * Returns maximum zoom level encoded in this tilemask.<br>
 * @return The maximum zoom level encoded in this tilemask.
 */
-(int)getMaxZoomLevel;
/**
 * Returns the bounding polygon of the tilemask.<br>
 * @param projection The projection to use.<br>
 * @return The bounding polygon of the tilemask area.
 */
-(NTMultiPolygonGeometry*)getBoundingPolygon: (NTProjection*)projection;
/**
 * Returns the status of the specified tile. This method can be used for fast testing whether a tile is part of the package.<br>
 * @param tile The tile to check.<br>
 * @return The status of the specified tile.
 */
-(enum NTPackageTileStatus)getTileStatus: (NTMapTile*)tile;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

