/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTColor.h"
#import "NTPolygon3DStyle.h"
#import "NTStyleBuilder.h"

/**
 * A builder class for Polygon3DStyle.
 */
__attribute__ ((visibility("default"))) @interface NTPolygon3DStyleBuilder : NTStyleBuilder
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 * @param cPtr The native pointer of the instance.
 * @param cMemoryOwn The ownership flag.
 * @return The new instance.
 */
/** @internal:nodoc: */
+(NTPolygon3DStyleBuilder*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a Polygon3DStyleBuilder object with all parameters set to defaults.
 */
-(id)init;
/**
 * Returns the color of the 3d polygon sides.<br>
 * @return The color of the 3d polygon sides.
 */
-(NTColor*)getSideColor;
/**
 * Sets the the color of the 3d polygon sides. The side color is also affected by lighting settings,<br>
 * so that sides with different orientation are distinguishable.<br>
 * @param sideColor The new color for the 3d polygon sides.
 */
-(void)setSideColor: (NTColor*)sideColor;
/**
 * Builds a new instance of the Polygon3DStyle object using previously set parameters.<br>
 * @return A new Polygon3DStyle object.
 */
-(NTPolygon3DStyle*)buildStyle;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
/** @internal:nodoc: */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
/** @internal:nodoc: */
-(void *)swigGetDirectorObject;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

