/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTScreenPos.h"
#import "NTScreenBounds.h"
#import "NTPopup.h"

/**
 * A container class that provides information how to draw the popup.
 */
__attribute__ ((visibility("default"))) @interface NTPopupDrawInfo : NSObject
{
  /** @internal:nodoc: */
  void *swigCPtr;
  /** @internal:nodoc: */
  BOOL swigCMemOwn;
}
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**  
 * Checks if this object is equal to the specified object.
 * @param object The reference object.
 * @return True when objects are equal, false otherwise.
 */
-(BOOL)isEqual:(id)object;

/**
 * Returns the hash value of this object.
 * @return The hash value of this object.
 */
-(NSUInteger)hash;

/**
 * Constructs a PopupClickInfo object from a click position and a vector element.<br>
 * @param anchorScreenPos The screen position of the anchor point of this popup in pixels.<br>
 * @param screenBounds The screen bounds for clipping the popup.<br>
 * @param popup The popup on which the click was performed.<br>
 * @param dpToPX The value used for converting display independent pixels (dp) to pixels (px).
 */
-(id)initWithAnchorScreenPos: (NTScreenPos*)anchorScreenPos screenBounds: (NTScreenBounds*)screenBounds popup: (NTPopup*)popup dpToPX: (float)dpToPX;
/**
 * Returns the screen position of the anchor point of this popup in pixels.<br>
 * @return The screen position of the anchor point of this popup in pixels.
 */
-(NTScreenPos*)getAnchorScreenPos;
/**
 * Returns the screen bounds, so that the popup can be clipped if neccessary.<br>
 * @return The screen bounds in pixels.
 */
-(NTScreenBounds*)getScreenBounds;
/**
 * Returns the popup to draw.<br>
 * @return The popup to draw.
 */
-(NTPopup*)getPopup;
/**
 * Returns the value used for converting display independent pixels (dp) to pixels (px).<br>
 * @return The value used for converting display independent pixels (dp) to pixels (px).
 */
-(float)getDPToPX;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

