/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTSearchRequest.h"
#import "NTTileDataSource.h"
#import "NTVectorTileFeatureCollection.h"
#import "NTVectorTileDecoder.h"
#import "NTProjection.h"

/**
 * A search service for finding features from the specified vector tile data source.
 */
__attribute__ ((visibility("default"))) @interface NTVectorTileSearchService : NSObject
{
  /** @internal:nodoc: */
  void *swigCPtr;
  /** @internal:nodoc: */
  BOOL swigCMemOwn;
}
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 * @param cPtr The native pointer of the instance.
 * @param cMemoryOwn The ownership flag.
 * @return The new instance.
 */
/** @internal:nodoc: */
+(NTVectorTileSearchService*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a VectorTileSearchService for the given vector data source and vector tile decoder.<br>
 * @param dataSource The vector data source to search from.<br>
 * @param tileDecoder The vector tile decoder to use for decoding the tiles.
 */
-(id)initWithDataSource: (NTTileDataSource*)dataSource tileDecoder: (NTVectorTileDecoder*)tileDecoder;
/**
 * Returns the tile data source of the search service.<br>
 * @return The tile data source of the search service.
 */
-(NTTileDataSource*)getDataSource;
/**
 * Returns the tile decoder used by the search service.<br>
 * @return The tile decoder used by the search service.
 */
-(NTVectorTileDecoder*)getTileDecoder;
/**
 * Returns the minimum zoom level of vector tiles used.<br>
 * By default the minimum zoom level is specified by data source and is usually 0.<br>
 * @return The minimum zoom level of vector tiles used.
 */
-(int)getMinZoom;
/**
 * Sets the minimum zoom level of vector tiles used.<br>
 * @param minZoom The new minimum zoom level.
 */
-(void)setMinZoom: (int)minZoom;
/**
 * Returns the maximum zoom level of vector tiles used.<br>
 * By default the maximum zoom level is specified by data source.<br>
 * @return The maximum zoom level of vector tiles used.
 */
-(int)getMaxZoom;
/**
 * Sets the maximum zoom level of vector tiles used.<br>
 * @param maxZoom The new maximum zoom level.
 */
-(void)setMaxZoom: (int)maxZoom;
/**
 * Searches for the features specified by search request from the vector tiles bound to the service.<br>
 * The zoom level range used for searching is specified using minZoom/maxZoom attributes of the search service.<br>
 * @param request The search request containing search filters.<br>
 * @return The resulting feature collection containing features matching the request.
 */
-(NTVectorTileFeatureCollection*)findFeatures: (NTSearchRequest*)request;
/**
 * Searches for the features specified by search request from the vector tiles bound to the service.<br>
 * The zoom level range used for searching is specified using minZoom/maxZoom attributes of the search service.<br>
 * @param request The search request containing search filters.<br>
 * @return The resulting feature collection containing features matching the request.
 */
-(NTVectorTileFeatureCollection*)findFeaturesSwigExplicitNTVectorTileSearchService: (NTSearchRequest*)request;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
/** @internal:nodoc: */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
/** @internal:nodoc: */
-(void *)swigGetDirectorObject;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

