/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTBinaryData.h"
#import "NTStringVector.h"
#import "NTAssetPackage.h"

/**
 * An asset package based on ZIP archived.<br>
 * Only deflate-based ZIP archives are supported.
 */
__attribute__ ((visibility("default"))) @interface NTZippedAssetPackage : NTAssetPackage
/** @internal:nodoc: */
-(void*)getCptr;
/** @internal:nodoc: */
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 * @param cPtr The native pointer of the instance.
 * @param cMemoryOwn The ownership flag.
 * @return The new instance.
 */
/** @internal:nodoc: */
+(NTZippedAssetPackage*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a ZIP asset package from the archived binary data.<br>
 * @param zipData The ZIP archive.
 */
-(id)initWithZipData: (NTBinaryData*)zipData;
/**
 * Constructs a ZIP asset package from the archived binary data and a fallback asset package.<br>
 * @param zipData The ZIP archive.<br>
 * @param baseAssetPackage The base asset package. If an asset is not found in the ZIP archive, base asset package is used.
 */
-(id)initWithZipData: (NTBinaryData*)zipData baseAssetPackage: (NTAssetPackage*)baseAssetPackage;
-(NTStringVector*)getLocalAssetNames;
-(NTStringVector*)getAssetNames;
-(NTBinaryData*)loadAsset: (NSString*)name;
/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
/** @internal:nodoc: */
-(long long)swigGetRawPtr;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
/** @internal:nodoc: */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
/** @internal:nodoc: */
-(void *)swigGetDirectorObject;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

